# source: https://www.localvisibilitysystem.com/docs/yelp-business-categories-list.pdf
import logging

yelp_coarse_aspect_categories = [
    "Afghan",
    "South African",
    "American (New)",
    "American (Traditional)",
    "Arabian",
    "Argentine",
    "Armenian",
    "Asian Fusion",
    "Australian",
    "Austrian",
    "Bangladeshi",
    "Barbeque",
    "Basque",
    "Belgian",
    "Brasseries",
    "Brazilian",
    "Breakfast & Brunch",
    "British",
    "Buffets",
    "Burgers",
    "Burmese",
    "Cafes",
    "Cafeteria",
    "Cajun/Creole",
    "Cambodian",
    "Caribbean",
    "Catalan",
    "Cheesesteaks",
    "Chicken Wings",
    "Chinese",
    "Comfort Food",
    "Creperies",
    "Cuban",
    "Czech",
    "Delis",
    "Diners",
    "Ethiopian",
    "Fast Food",
    "Filipino",
    "Fish & Chips",
    "Fondue",
    "Food Court",
    "Food Stands",
    "French",
    "Gastropubs",
    "German",
    "Gluten-Free",
    "Greek",
    "Halal",
    "Hawaiian",
    "Himalayan/Nepalese",
    "Hot Dogs",
    "Hot Pot",
    "Hungarian",
    "Iberian",
    "Indian",
    "Indonesian",
    "Irish",
    "Italian",
    "Japanese",
    "Korean",
    "Kosher",
    "Laotian",
    "Latin American",
    "Live/Raw Food",
    "Malaysian",
    "Mediterranean",
    "Mexican",
    "Middle Eastern",
    "Modern European",
    "Mongolian",
    "Pakistani",
    "Persian/Iranian",
    "Peruvian",
    "Pizza",
    "Polish",
    "Portuguese",
    "Russian",
    "Salad",
    "Sandwiches",
    "Scandinavian",
    "Scottish",
    "Seafood",
    "Singaporean",
    "Slovakian",
    "Soul Food",
    "Soup",
    "Southern",
    "Spanish",
    "Steakhouses",
    "Sushi Bars",
    "Taiwanese",
    "Tapas Bars",
    "Tapas/Small Plates",
    "Tex-Mex",
    "Thai",
    "Turkish",
    "Ukranian",
    "Vegan",
    "Vegetarian",
    "Vietnamese",
]
yelp_refined_aspect_categories = [
    "Afghan:African",
    "Afghan:Senegales",
    "South African",
    "American (New)",
    "American (Traditional)",
    "Arabian",
    "Argentine",
    "Armenian",
    "Asian Fusion",
    "Australian",
    "Austrian",
    "Bangladeshi",
    "Barbeque",
    "Basque",
    "Belgian",
    "Brasseries",
    "Brazilian",
    "Breakfast & Brunch",
    "British",
    "Buffets",
    "Burgers",
    "Burmese",
    "Cafes",
    "Cafeteria",
    "Cajun/Creole",
    "Cambodian",
    "Caribbean:Dominican",
    "Caribbean:Haitian",
    "Caribbean:Puerto Rican",
    "Caribbean:Trinidadian",
    "Catalan",
    "Cheesesteaks",
    "Chicken Wings",
    "Chinese:Cantonese",
    "Chinese:Dim Sum",
    "Chinese:Shanghainese",
    "Chinese:Szechuan",
    "Comfort Food",
    "Creperies",
    "Cuban",
    "Czech",
    "Delis",
    "Diners",
    "Ethiopian",
    "Fast Food",
    "Filipino",
    "Fish & Chips",
    "Fondue",
    "Food Court",
    "Food Stands",
    "French",
    "Gastropubs",
    "German",
    "Gluten-Free",
    "Greek",
    "Halal",
    "Hawaiian",
    "Himalayan/Nepalese",
    "Hot Dogs",
    "Hot Pot",
    "Hungarian",
    "Iberian",
    "Indian",
    "Indonesian",
    "Irish",
    "Italian",
    "Japanese",
    "Korean",
    "Kosher",
    "Laotian",
    "Latin American:Columbian",
    "Latin American:Salvadoran",
    "Latin American:Venezuelan",
    "Live/Raw Food",
    "Malaysian",
    "Mediterranean",
    "Mexican",
    "Middle Eastern:Egyptian",
    "Middle Eastern:Lebanese",
    "Modern European",
    "Mongolian",
    "Pakistani",
    "Persian/Iranian",
    "Peruvian",
    "Pizza",
    "Polish",
    "Portuguese",
    "Russian",
    "Salad",
    "Sandwiches",
    "Scandinavian",
    "Scottish",
    "Seafood",
    "Singaporean",
    "Slovakian",
    "Soul Food",
    "Soup",
    "Southern",
    "Spanish",
    "Steakhouses",
    "Sushi Bars",
    "Taiwanese",
    "Tapas Bars",
    "Tapas/Small Plates",
    "Tex-Mex",
    "Thai",
    "Turkish",
    "Ukranian",
    "Vegan",
    "Vegetarian",
    "Vietnamese",
]

yelp_condensed_map = {
    "African Cuisine": ["Ethiopian", "South African"],
    "American Cuisine": [
        "American (New)",
        "American (Traditional)",
        "Burgers",
        "Cajun/Creole",
        "Cheesesteaks",
        "Chicken Wings",
        "Fast Food",
        "Hot Dogs",
        "Southern",
        "Tex-Mex",
    ],
    "Asian Cuisine": ["Asian Fusion", "Australian", "Hawaiian"],
    "Barbecue and Steakhouses": ["Barbeque", "Steakhouses"],
    "Breakfast and Cafes": [
        "Breakfast & Brunch",
        "Buffets",
        "Cafes",
        "Cafeteria",
        "Delis",
        "Sandwiches",
        "Soup",
    ],
    "Burmese and Mongolian Cuisine": ["Burmese", "Mongolian"],
    "Chinese Cuisine": ["Chinese", "Taiwanese"],
    "Comfort Food and Diners": ["Comfort Food", "Diners", "Soul Food"],
    "European Cuisine": [
        "Austrian",
        "Basque",
        "Belgian",
        "British",
        "Catalan",
        "Creperies",
        "Czech",
        "Fish & Chips",
        "Fondue",
        "French",
        "German",
        "Hungarian",
        "Iberian",
        "Irish",
        "Italian",
        "Pizza",
        "Polish",
        "Portuguese",
        "Russian",
        "Scandinavian",
        "Scottish",
        "Slovakian",
        "Spanish",
        "Ukranian",
    ],
    "Food Court and Stands": ["Food Court", "Food Stands"],
    "Gastropubs and Modern European": ["Gastropubs", "Modern European"],
    "Greek and Mediterranean Cuisine": ["Greek", "Mediterranean"],
    "Halal and Kosher": ["Halal", "Kosher"],
    # "miscellaneous": [
    #     "Himalayan and Nepalese Cuisine",
    #     "Himalayan/Nepalese",
    #     "Brasseries",
    # ],
    "Hot Pot": ["Hot Pot"],
    "Japanese and Sushi": ["Japanese", "Sushi Bars"],
    "Korean Cuisine": ["Korean"],
    "Latin American Cuisine": [
        "Argentine",
        "Brazilian",
        "Caribbean",
        "Cuban",
        "Latin American",
        "Mexican",
        "Peruvian",
    ],
    "Live/Raw Food and Salad": ["Live/Raw Food", "Salad"],
    "Middle Eastern Cuisine": [
        "Afghan",
        "Arabian",
        "Armenian",
        "Middle Eastern",
        "Moddle Eastern",
        "Persian/Iranian",
        "Turkish",
    ],
    "Seafood": ["Seafood"],
    "South Asian Cuisine": ["Bangladeshi", "Indian", "Pakistani"],
    "Southeast Asian Cuisine": [
        "Cambodian",
        "Filipino",
        "Indonesian",
        "Laotian",
        "Malaysian",
        "Singaporean",
        "Thai",
        "Vietnamese",
    ],
    "Gluten-Free,Vegan,Vegetarian": ["Gluten-Free", "Vegan", "Vegetarian"],
    "Tapas Bars": ["Tapas Bars", "Tapas/Small Plates"],
}


# https://alt.qcri.org/semeval2016/task5/data/uploads/absa2016_annotationguidelines.pdf
semeval16_refined_aspect_categories = [
    # "reastaurant:general",
    # "reastaurant:prices",
    # "reastaurant:miscellaneous", # restarant: opns about the evaluated restaurant as a whole
    "food:prices",
    "food:quality",
    "food:style_options",  # yelp aspect categories are generally this category
    "drinks:prices",
    "drinks:quality",
    "ambience:general",
    "service:general",
    "location:general",
]

semeval16_coarse_aspect_categories = [
    # "reastaurant:general",
    # "reastaurant:prices",
    # "reastaurant:miscellaneous", # restaurant is too general to be used
    "service",
    "location",
    # "food & drinks",
]


def get_yelp_label_list(use_fine_grained: bool = True):
    label_list = (
        yelp_coarse_aspect_categories
        if not use_fine_grained
        else yelp_refined_aspect_categories
    )
    if use_fine_grained:
        # use tertiary level aspect categories if available
        logging.info(f"Using [yelp] refined label list of length {len(label_list)}")
    else:
        # only use secondary level aspect categories
        logging.info(f"Using [yelp] coarse label list of length {len(label_list)}")
    return label_list


def get_semeval16_label_list(use_fine_grained: bool = True):
    label_list = (
        semeval16_coarse_aspect_categories
        if not use_fine_grained
        else semeval16_refined_aspect_categories
    )
    if use_fine_grained:
        # use tertiary level aspect categories if available
        logging.info(
            f"Using [semeval16] refined label list of length {len(label_list)}"
        )
    else:
        # only use secondary level aspect categories
        logging.info(f"Using [semeval16] coarse label list of length {len(label_list)}")
    return label_list


def get_mixed_list():
    coarse_semeval = semeval16_coarse_aspect_categories
    # remove food & drinks
    yelp = yelp_condensed_map.keys()
    yelp = list(yelp)
    # add yelp condensed
    return list(set(coarse_semeval + yelp))


def convert_refined_to_coarse(refined_label: str):
    """turn refined label to coarse label; applicable to both yelp and semeval16"""
    return refined_label.split(":")[0]


def get_simplified_list():
    list_ = [
        "food:American Cuisine",
        "food:Barbecue and Steakhouses",
        "food:Breakfast and Cafes",
        "food:Chinese Cuisine",
        "food:Comfort Food and Diners",
        "food:European Cuisine",
        "food:Gluten-Free,Vegan,Vegetarian",
        "food:Greek and Mediterranean Cuisine",
        "food:Japanese and Sushi",
        "food:Korean Cuisine",
        "food:Latin American Cuisine",
        "food:Live/Raw Food and Salad",
        "food:Middle Eastern Cuisine",
        "food:Seafood",
        "food:Asian Cuisine",
        "food:Bars",
        "location",
        "service",
    ]
    return list_
